### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (21584x1 and 3x1)

### ISSUE THREAD

**Issue by Lzyin** [CVLAB-Unibo/MM2D3D#3]
Excuse me, a runtime error is reported when I run the script `CUDA_VISIBLE_DEVICES=0,1 python experiments_USA_SING/rgbd_rgbxyz_sigmoid_for_rgb/run.py`:
**RuntimeError: mat1 and mat2 shapes cannot be multiplied (21584x1 and 3x1)**

I run the` lib/dataset/preprocess_nuscenes_lidarseg.py` script to prepare the data.

I check and find that the data shape of data_batch["x"][1] is 21584x1 (located on line 46 of the _experiments_USA_SING/rgbd_rgbxyz_sigmoid_for_rgb/3d_net/model.py_ file), but the mapping of the linear layer is 3 ->1:
`mask_rgb = self.linear_rgb_mask(data_batch["x"][1])`
`self.linear_rgb_mask = nn.Linear(3, 1)`

Also, can you clarify the version of the package (e.g. pytorch-lightning, hydra, etc.)?

Thanks for your reply and help!

**Comment by Lzyin** [comment]
@adricarda I sincerely hope to get your reply.

**Comment by HwiJeong-Lee** [comment]
Excuse me, I'm also experiencing the same error with you. 
Can you let me know how you solved this issue?
I would be very grateful if you could help me.

Thanks for your reply!
